"""support fisherman phone authentication

Revision ID: 558c00fd6f59
Revises: 6f31519d5bb0
Create Date: 2026-09-25 02:47:26.818314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '558c00fd6f59'
down_revision: Union[str, Sequence[str], None] = '6f31519d5bb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('fisher_id', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('auth_method', sa.String(length=20), server_default='PASSWORD', nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_fisher_id'), 'users', ['fisher_id'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_fisher_id'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
    op.drop_column('users', 'auth_method')
    op.drop_column('users', 'fisher_id')
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
