"""create initial orca tables

Revision ID: 6f31519d5bb0
Revises: 
Create Date: 2026-09-24 21:07:05.093894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '6f31519d5bb0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('FISHERMAN', 'RESEARCHER', 'AUTHORITY', 'ADMIN')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('fisherman_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('home_landing_centre', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('home_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
   
    op.create_index(op.f('ix_fisherman_profiles_user_id'), 'fisherman_profiles', ['user_id'], unique=True)
    op.create_table('vessels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('vessel_type', sa.String(length=100), nullable=True),
    sa.Column('length_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('beam_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cruising_speed_knots', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('persons_onboard_default', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('beam_m IS NULL OR beam_m > 0', name='ck_vessels_beam_positive'),
    sa.CheckConstraint('cruising_speed_knots IS NULL OR cruising_speed_knots > 0', name='ck_vessels_speed_positive'),
    sa.CheckConstraint('length_m IS NULL OR length_m > 0', name='ck_vessels_length_positive'),
    sa.CheckConstraint('persons_onboard_default > 0', name='ck_vessels_persons_positive'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_vessels_owner_id'), 'vessels', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vessels_owner_id'), table_name='vessels')
    op.drop_table('vessels')
    op.drop_index(op.f('ix_fisherman_profiles_user_id'), table_name='fisherman_profiles')
    op.drop_table('fisherman_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
