"""support fisherman phone authentication

Revision ID: 89e6e9efa6bc
Revises: 558c00fd6f59
Create Date: 2026-09-25 02:53:05.335410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e6e9efa6bc'
down_revision: Union[str, Sequence[str], None] = '558c00fd6f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
